sudo: false
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - npm install rethinkdb
  - npm install immigration
  - npm install

node_js:
  - '4'
  - stable

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
